"""empty message

Revision ID: 9be906200aa7
Revises: 5c0628ed15d7
Create Date: 2021-11-10 12:32:46.752219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be906200aa7'
down_revision = '5c0628ed15d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('path_file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'path_file')
    # ### end Alembic commands ###
