"""empty message

Revision ID: abe297889135
Revises: 9be906200aa7
Create Date: 2021-11-10 12:41:00.132419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe297889135'
down_revision = '9be906200aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('filename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'filename')
    # ### end Alembic commands ###
